spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/heatrun
    username: heatrun
    password: heatrun
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate        # Flyway가 스키마 관리하므로 validate (검증)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  flyway:
    enabled: true  # 임시 비활성화 # Flyway가 스키마 관리
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6380

server:
  port: 8088