-- =====================================================
-- HeatRun 초기 스키마
-- V1__init_schema.sql
-- =====================================================

-- PostGIS 확장 활성화
CREATE EXTENSION IF NOT EXISTS postgis;

-- =====================================================
-- users
-- =====================================================
CREATE TABLE users
(
    id                   UUID          NOT NULL DEFAULT gen_random_uuid(),
    email                VARCHAR(100)  NOT NULL,
    nickname             VARCHAR(30)   NOT NULL,
    password             VARCHAR(255),
    profile_image_url    VARCHAR(500),
    provider             VARCHAR(20)   NOT NULL,
    provider_id          VARCHAR(255),
    privacy_zone_point   GEOMETRY(Point, 4326),
    privacy_zone_radius  INT           NOT NULL DEFAULT 500,
    location_share_scope VARCHAR(20)   NOT NULL DEFAULT 'CREW_ALL',
    status               VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    created_at           TIMESTAMP     NOT NULL DEFAULT now(),
    updated_at           TIMESTAMP     NOT NULL DEFAULT now(),

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uc_users_email UNIQUE (email)
);

-- =====================================================
-- running_sessions
-- =====================================================
CREATE TABLE running_sessions
(
    id                    UUID         NOT NULL DEFAULT gen_random_uuid(),
    user_id               UUID         NOT NULL,
    total_distance_km     DOUBLE PRECISION,
    duration_seconds      INT,
    avg_pace              DOUBLE PRECISION,
    calories_burned       DOUBLE PRECISION,
    weather_condition     VARCHAR(20),
    status                VARCHAR(20)  NOT NULL DEFAULT 'IN_PROGRESS',
    ghost_session_id      UUID,
    started_at            TIMESTAMP    NOT NULL,
    ended_at              TIMESTAMP,

    CONSTRAINT pk_running_session PRIMARY KEY (id),
    CONSTRAINT fk_running_session_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_running_session_ghost FOREIGN KEY (ghost_session_id) REFERENCES running_sessions (id)
);

COMMENT ON TABLE running_sessions IS '러닝 세션 1회 러닝 = 1 row';
COMMENT ON COLUMN running_sessions.avg_pace IS '평균 페이스 초/km';
COMMENT ON COLUMN running_sessions.ghost_session_id IS '고스트 러닝 시 참조 세션 없으면 NULL';

CREATE INDEX idx_running_session_user ON running_sessions (user_id, started_at DESC);

-- =====================================================
-- route_points
-- GPS 좌표 시계열 저장 (대용량 BIGSERIAL)
-- =====================================================
CREATE TABLE route_points
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id            UUID                  NOT NULL,
    location              GEOMETRY(Point, 4326) NOT NULL,
    altitude              DOUBLE PRECISION,
    speed                 DOUBLE PRECISION,
    sequence_number       INT                   NOT NULL,
    recorded_at           TIMESTAMP             NOT NULL,
    created_at            TIMESTAMP             NOT NULL DEFAULT now(),

    CONSTRAINT pk_route_points PRIMARY KEY (id),
    CONSTRAINT fk_route_points_session FOREIGN KEY (session_id) REFERENCES running_sessions (id)
);
COMMENT ON TABLE route_points IS 'GPS 좌표 시계열 러닝 1회당 약 720 row';
COMMENT ON COLUMN route_points.sequence_number IS '경로 재현 시 순서 보장';
COMMENT ON COLUMN route_points.location IS 'PostGIS Point WGS84 SRID 4326';

CREATE INDEX idx_route_points_session_sequence ON route_points (session_id, sequence_number);
CREATE INDEX idx_route_points_recorded_at ON route_points (recorded_at);

-- =====================================================
-- heatmap_tiles
-- 유저 방문 지도 격자 누적 (대용량 BIGSERIAL)
-- =====================================================
CREATE TABLE heatmap_tiles
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          UUID              NOT NULL,
    tile_x           INT               NOT NULL,
    tile_y           INT               NOT NULL,
    zoom_level       INT               NOT NULL,
    visit_count      INT               NOT NULL DEFAULT 1,
    intensity        DOUBLE PRECISION  NOT NULL DEFAULT 1.0,
    is_running       BOOLEAN           NOT NULL DEFAULT true,
    last_visited_at  TIMESTAMP         NOT NULL,
    created_at       TIMESTAMP         NOT NULL DEFAULT now(),
    updated_at       TIMESTAMP         NOT NULL DEFAULT now(),

    CONSTRAINT pk_heatmap_tiles PRIMARY KEY (id),
    CONSTRAINT fk_heatmap_tiles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_heatmap_user_tile_zoom UNIQUE (user_id, tile_x, tile_y, zoom_level)
);

COMMENT ON TABLE heatmap_tiles IS '히트맵 지도 격자 유저별 방문 누적';
COMMENT ON COLUMN heatmap_tiles.intensity IS '0.0~1.0 반문 횟수 기반 계산';
COMMENT ON COLUMN heatmap_tiles.is_running IS 'true 러닝 false 보행(만보기)';

CREATE INDEX idx_heatmap_user_zoom_tile ON heatmap_tiles (user_id, zoom_level, tile_x, tile_y);

-- =====================================================
-- ghost_records
-- 러닝 세션에서 파생된 고스트 기록
-- =====================================================
CREATE TABLE ghost_records
(
    id                    UUID         NOT NULL DEFAULT gen_random_uuid(),
    original_session_id   UUID         NOT NULL,
    owner_user_id         UUID         NOT NULL,
    record_type           VARCHAR(20)  NOT NULL,
    is_public             BOOLEAN      NOT NULL DEFAULT false,
    total_distance_km
)