-- =====================================================
-- HeatRun 초기 스키마
-- V1__init_schema.sql
-- =====================================================

-- PostGIS 확장 활성화
CREATE EXTENSION IF NOT EXISTS postgis;

-- =====================================================
-- users
-- =====================================================
CREATE TABLE users
(
    id                   UUID          NOT NULL DEFAULT gen_random_uuid(),
    email                VARCHAR(100)  NOT NULL,
    nickname             VARCHAR(30)   NOT NULL,
    password             VARCHAR(255),
    profile_image_url    VARCHAR(500),
    provider             VARCHAR(20)   NOT NULL,
    provider_id          VARCHAR(255),
    privacy_zone_point   GEOMETRY(Point, 4326),
    privacy_zone_radius  INT           NOT NULL DEFAULT 500,
    location_share_scope VARCHAR(20)   NOT NULL DEFAULT 'CREW_ALL',
    status               VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    created_at           TIMESTAMP     NOT NULL DEFAULT now(),
    updated_at           TIMESTAMP     NOT NULL DEFAULT now(),

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uc_users_email UNIQUE (email)
);

-- =====================================================
-- running_sessions
-- =====================================================
CREATE TABLE running_sessions
(
    id                    UUID         NOT NULL DEFAULT gen_random_uuid(),
    user_id               UUID         NOT NULL,
    total_distance_km     DOUBLE PRECISION,
    duration_seconds      INT,
    avg_pace              DOUBLE PRECISION,
    calories_burned       DOUBLE PRECISION,
    weather_condition     VARCHAR(20),
    status                VARCHAR(20)  NOT NULL DEFAULT 'IN_PROGRESS',
    ghost_session_id      UUID,
    started_at            TIMESTAMP    NOT NULL,
    ended_at              TIMESTAMP,

    CONSTRAINT pk_running_session PRIMARY KEY (id),
    CONSTRAINT fk_running_session_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_running_session_ghost FOREIGN KEY (ghost_session_id) REFERENCES running_sessions (id)
);

COMMENT ON TABLE running_sessions IS '러닝 세션 1회 러닝 = 1 row';
COMMENT ON COLUMN running_sessions.avg_pace IS '평균 페이스 초/km';
COMMENT ON COLUMN running_sessions.ghost_session_id IS '고스트 러닝 시 참조 세션 없으면 NULL';

CREATE INDEX idx_running_session_user ON running_sessions (user_id, started_at DESC);

-- =====================================================
-- route_points
-- GPS 좌표 시계열 저장 (대용량 BIGSERIAL)
-- =====================================================
CREATE TABLE route_points
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id            UUID                  NOT NULL,
    location              GEOMETRY(Point, 4326) NOT NULL,
    altitude              DOUBLE PRECISION,
    speed                 DOUBLE PRECISION,
    sequence_number       INT                   NOT NULL,
    recorded_at           TIMESTAMP             NOT NULL,
    created_at            TIMESTAMP             NOT NULL DEFAULT now(),

    CONSTRAINT pk_route_points PRIMARY KEY (id),
    CONSTRAINT fk_route_points_session FOREIGN KEY (session_id) REFERENCES running_sessions (id)
);
COMMENT ON TABLE route_points IS 'GPS 좌표 시계열 러닝 1회당 약 720 row';
COMMENT ON COLUMN route_points.sequence_number IS '경로 재현 시 순서 보장';
COMMENT ON COLUMN route_points.location IS 'PostGIS Point WGS84 SRID 4326';

CREATE INDEX idx_route_points_session_sequence ON route_points (session_id, sequence_number);
CREATE INDEX idx_route_points_recorded_at ON route_points (recorded_at);

-- =====================================================
-- heatmap_tiles
-- 유저 방문 지도 격자 누적 (대용량 BIGSERIAL)
-- =====================================================
CREATE TABLE heatmap_tiles
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          UUID              NOT NULL,
    tile_x           INT               NOT NULL,
    tile_y           INT               NOT NULL,
    zoom_level       INT               NOT NULL,
    visit_count      INT               NOT NULL DEFAULT 1,
    intensity        DOUBLE PRECISION  NOT NULL DEFAULT 1.0,
    is_running       BOOLEAN           NOT NULL DEFAULT true,
    last_visited_at  TIMESTAMP         NOT NULL,
    created_at       TIMESTAMP         NOT NULL DEFAULT now(),
    updated_at       TIMESTAMP         NOT NULL DEFAULT now(),

    CONSTRAINT pk_heatmap_tiles PRIMARY KEY (id),
    CONSTRAINT fk_heatmap_tiles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_heatmap_user_tile_zoom UNIQUE (user_id, tile_x, tile_y, zoom_level)
);

COMMENT ON TABLE heatmap_tiles IS '히트맵 지도 격자 유저별 방문 누적';
COMMENT ON COLUMN heatmap_tiles.intensity IS '0.0~1.0 반문 횟수 기반 계산';
COMMENT ON COLUMN heatmap_tiles.is_running IS 'true 러닝 false 보행(만보기)';

CREATE INDEX idx_heatmap_user_zoom_tile ON heatmap_tiles (user_id, zoom_level, tile_x, tile_y);

-- =====================================================
-- ghost_records
-- 러닝 세션에서 파생된 고스트 기록
-- =====================================================
CREATE TABLE ghost_records
(
    id                    UUID         NOT NULL DEFAULT gen_random_uuid(),
    original_session_id   UUID         NOT NULL,
    owner_user_id         UUID         NOT NULL,
    record_type           VARCHAR(20)  NOT NULL,
    is_public             BOOLEAN      NOT NULL DEFAULT false,
    total_distance_km     DOUBLE PRECISION,
    duration_seconds      INT,

    CONSTRAINT pk_ghost_records PRIMARY KEY (id),
    CONSTRAINT fk_ghost_records_session FOREIGN KEY (original_session_id) REFERENCES running_sessions (id),
    CONSTRAINT fk_ghost_records_user FOREIGN KEY (owner_user_id) REFERENCES users (id)
);

COMMENT ON TABLE ghost_records IS '고스트 기록 PB 자동등록 또는 수동 공개등록';
COMMENT ON COLUMN ghost_records.record_type IS 'PERSONAL_BEST/MANUAL_PUBLIC';

-- =====================================================
-- pedometer_logs
-- 만보기 일별 1 row
-- =====================================================
CREATE TABLE pedometer_logs
(
    id                   UUID         NOT NULL DEFAULT gen_random_uuid(),
    user_id              UUID         NOT NULL,
    log_date             DATE         NOT NULL,
    step_count           INT          NOT NULL DEFAULT 0,
    daily_goal           INT          NOT NULL DEFAULT 10000,
    goal_achieved        BOOLEAN      NOT NULL DEFAULT false,
    distance_km          DOUBLE PRECISION,

    CONSTRAINT pk_pedometer_logs PRIMARY KEY (id),
    CONSTRAINT fk_pedometer_logs_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_pedometer_user_date UNIQUE (user_id, log_date)
);

COMMENT ON TABLE pedometer_logs IS '만보기 일별 걸음 수 하루 1row';
COMMENT ON COLUMN pedometer_logs.distance_km IS '걸음수 x 0.00075 평균 보폭 0.75m';

-- =====================================================
-- crews
-- =====================================================
CREATE TABLE crews
(
    id                  UUID          NOT NULL DEFAULT gen_random_uuid(),
    leader_user_id      UUID          NOT NULL,
    name                VARCHAR(50)   NOT NULL,
    description         VARCHAR(200),
    visibility          VARCHAR(20)   NOT NULL DEFAULT 'PUBLIC',
    max_members         INT           NOT NULL DEFAULT 50,
    member_count        INT           NOT NULL DEFAULT 1,

    CONSTRAINT pk_crews PRIMARY KEY (id),
    CONSTRAINT fk_crews_leader FOREIGN KEY (leader_user_id) REFERENCES users (id),
    CONSTRAINT uc_crews_name UNIQUE (name)
);

COMMENT ON TABLE crews IS '크루 최대 50명 MVP 기준';
COMMENT ON COLUMN crews.visibility IS 'PUBLIC 검색기능 PRIVATE 초대전용';

-- =====================================================
-- crew_members
-- Crew 와 User 중간 테이블
-- =====================================================
CREATE TABLE crew_members
(
    id                    UUID         NOT NULL DEFAULT gen_random_uuid(),
    crew_id               UUID         NOT NULL,
    user_id               UUID         NOT NULL,
    role                  VARCHAR(20)  NOT NULL DEFAULT 'MEMBER',
    location_share_scope  VARCHAR(20)  NOT NULL DEFAULT 'CREW_ALL',
    joined_at             TIMESTAMP    NOT NULL,

    CONSTRAINT pk_crew_members PRIMARY KEY (id),
    CONSTRAINT fk_crew_members_crew FOREIGN KEY (crew_id) REFERENCES crews (id),
    CONSTRAINT fk_crew_members_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_crew_member UNIQUE (crew_id, user_id)
);

COMMENT ON TABLE crew_members IS '크루 멤버 중간 테이블';
COMMENT ON COLUMN crew_members.location_share_scope IS '크루별 위치 공유 범위 User 기본값 오버라이드';

-- =====================================================
-- crew_cheers
-- 응원 로그 (내부 전용 BIGSERIAL)
-- =====================================================
CREATE TABLE crew_cheers
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sender_id       UUID          NOT NULL,
    receiver_id     UUID          NOT NULL,
    crew_id         UUID          NOT NULL,
    cheer_type      VARCHAR(20)   NOT NULL,
    sent_at         TIMESTAMP     NOT NULL,
    created_at      TIMESTAMP     NOT NULL DEFAULT now(),

    CONSTRAINT pk_crew_cheers PRIMARY KEY (id),
    CONSTRAINT fk_crew_cheers_sender FOREIGN KEY (sender_id) REFERENCES users (id),
    CONSTRAINT fk_crew_cheers_receiver FOREIGN KEY (receiver_id) REFERENCES users (id),
    CONSTRAINT fk_crew_cheers_crew FOREIGN KEY (crew_id) REFERENCES crews (id)
);

COMMENT ON TABLE crew_cheers IS '크루 응원 로그 PUSH/SOUND';

CREATE INDEX idx_crew_cheers_receiver ON crew_cheers (receiver_id, sent_at DESC);

-- =====================================================
-- user_levels
-- 유저당 1 row (1:1)
-- =====================================================
CREATE TABLE user_levels
(
    id                  UUID    NOT NULL DEFAULT gen_random_uuid(),
    user_id             UUID    NOT NULL,
    current_level       INT     NOT NULL DEFAULT 1,
    total_exp           INT     NOT NULL DEFAULT 0,
    exp_to_next_level   INT     NOT NULL DEFAULT 100,

    CONSTRAINT pk_user_levels PRIMARY KEY (id),
    CONSTRAINT fk_user_levels_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uc_user_levels_user UNIQUE (user_id)
);

COMMENT ON TABLE user_levels IS '유저 레벨 경험치 유저당 1 row';
COMMENT ON COLUMN user_levels.exp_to_next_level IS '현재레벨 x 100으로 증가';

-- =====================================================
-- exp_logs
-- 경험치 획득 이력 (내부 로그 BIGSERIAL)
-- =====================================================
CREATE TABLE exp_logs
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        UUID         NOT NULL,
    exp_earned     INT          NOT NULL,
    source_type    VARCHAR(30)  NOT NULL,
    source_id      UUID,
    created_at     TIMESTAMP    NOT NULL DEFAULT now(),

    CONSTRAINT pk_exp_logs PRIMARY KEY (id),
    CONSTRAINT fk_exp_logs_user FOREIGN KEY (user_id) REFERENCES users (id)
);

COMMENT ON TABLE exp_logs IS '경험치 획득 이력 지급 버그 롤백 근거';
COMMENT ON COLUMN exp_logs.source_type IS 'RUNNING/GHOST_OVERTAKE/PEDOMETER/EXPLORE/STREAK';
COMMENT ON COLUMN exp_logs.source_id IS '출처 ID 없으면 NULL';

CREATE INDEX idx_exp_logs_user_created ON exp_logs (user_id, created_at DESC);
CREATE INDEX idx_exp_logs_source ON exp_logs (source_type, source_id);

-- =====================================================
-- titles
-- 칭호 마스터 데이터
-- =====================================================
CREATE TABLE titles
(
    id              UUID          NOT NULL DEFAULT gen_random_uuid(),
    code            VARCHAR(50)   NOT NULL,
    name            VARCHAR(50)   NOT NULL,
    description     VARCHAR(200),
    condition_type  VARCHAR(30)   NOT NULL,
    condition_value INT           NOT NULL,
    icon_url        VARCHAR(500),
    is_limited      BOOLEAN       NOT NULL DEFAULT false,

    CONSTRAINT pk_titles PRIMARY KEY (id),
    CONSTRAINT uc_titles_code UNIQUE (code)
);

COMMENT ON TABLE titles IS '칭호 마스터 데이터 관리자 등록';
COMMENT ON COLUMN titles.condition_type IS 'GHOST_OVERTAKE/EARLY_MORNING/RAINY_RUN/EXPLORE/STREAK';
COMMENT ON COLUMN titles.condition_value IS '조건 달성 기준값';

-- =====================================================
-- user_titles
-- 유저 보유 칭호 (내부 중간 테이블 BIGSERIAL)
-- =====================================================
CREATE TABLE user_titles
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      UUID        NOT NULL,
    title_id     UUID        NOT NULL,
    is_equipped  BOOLEAN     NOT NULL DEFAULT false,
    earned_at    TIMESTAMP   NOT NULL,
    created_at   TIMESTAMP   NOT NULL DEFAULT now(),

    CONSTRAINT pk_user_titles PRIMARY KEY (id),
    CONSTRAINT fk_user_titles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_titles_title FOREIGN KEY (title_id) REFERENCES titles (id),
    CONSTRAINT uk_user_title UNIQUE (user_id, title_id)
);

COMMENT ON TABLE user_titles IS '유저 보유 칭호 최대 2개 장착 가능';

CREATE INDEX idx_user_titles_user ON user_titles (user_id);

